#!/bin/sh
# postrm script for easyfind-client
#
# see: dh_installdeb(1)

set -e

case "$1" in
    remove)
    deluser --quiet --system easyfind
    delgroup --quiet --system --only-if-empty easyfind || true
    ;;

    purge)
    rm -rf /var/lib/easyfind
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
